stages:
  - deploy

deploy configuration:
  stage: deploy
  script:
    # DB variables
    - export POSTGRES_USER=kong
    - export POSTGRES_DB=kong-db
    - export POSTGRES_USER_PASSWD=${POSTGRES_USER_PASSWD}
    # KONG Token Secret
    - export KONG_TOKEN_SECRET=${KONG_SECRET}
    # Graylog Opts
    - export GRAYLOG_ADDR=${GRAYLOG_ADDR}
    - export GRAYLOG_PORT=${GRAYLOG_PORT}
    # Launch stack
    - docker stack deploy -c docker-compose.yml kong-api
  only:
    - master
  tags:
    - kong-gw
