stages:
  - validate
  - deploy

before_script:
    # KONG service replicas
    - export KONG_REPLICAS=${KONG_REPLICAS}
    # DB variables
    - export POSTGRES_USER=kong
    - export POSTGRES_DB=kong-db
    - export POSTGRES_USER_PASSWD=${POSTGRES_USER_PASSWD}
    # KONGA Token Secret
    - export KONGA_TOKEN_SECRET=${KONGA_SECRET}
    # Graylog Opts
    - export GRAYLOG_ADDR=${GRAYLOG_ADDR}
    - export GRAYLOG_PORT=${GRAYLOG_PORT}
    - export ENVIRONMENT=${CI_ENVIRONMENT_NAME}

validate configuration:
  stage: validate
  script:
    # Validate stdout configuration
    - docker-compose -f docker-compose-stdout.yml config -q
    # Validate configuration
    - docker-compose config -q
  tags:
    - kong-gw

deploy stack production:
  stage: deploy
  script:
    # Launch stack
    - docker stack deploy -c docker-compose.yml kong-api
  environment:
    name: production
    url: https://kong.apifonica.com
  only:
    - master
  tags:
    - kong-gw
