stages:
  - validate
  - deploy

before_script:
    # DB variables
    - export POSTGRES_USER=kong
    - export POSTGRES_DB=kong-db
    - export POSTGRES_USER_PASSWD=${POSTGRES_USER_PASSWD}
    # KONG Token Secret
    - export KONG_TOKEN_SECRET=${KONG_SECRET}
    # Graylog Opts
    - export GRAYLOG_ADDR=${GRAYLOG_ADDR}
    - export GRAYLOG_PORT=${GRAYLOG_PORT}
    - export ENVIRONMENT=${CI_ENVIRONMENT_NAME}

validate configuration:
  stage: validate
  script:
    # Validate configuration
    - docker-compose config -q
  tags:
    - kong-gw

deploy stack production:
  stage: deploy
  script:
    # Launch stack
    - docker stack deploy -c docker-compose.yml kong-api
  environment:
    name: production
    url: https://kong.apifonica.com
  only:
    - master
  tags:
    - kong-gw
