version: "3.7"
services:
  # Database
  kong-database:
    image: postgres:9.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER_PASSWD=${POSTGRES_USER_PASSWD}
    ports:
      - 5432:5432
    networks:
      - kong-net

  # Kong
  kong:
    image: kong:1.2.1-alpine
    depends_on:
      - kong-database
    restart: unless-stopped
    deploy:
      replicas: 10
    environment:
      - KONG-DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=${POSTGRES_DB}
      - KONG_PG_USER=${POSTGRES_USER}
      - KONG_PG_PASSWORD=${POSTGRES_USER_PASSWD}
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    networks:
      - kong-net

  #Kong migrations
  kong-migration:
    image: kong:1.2.1-alpine
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=${POSTGRES_DB}
      - KONG_PG_USER=${POSTGRES_USER}
    command: ash -c "sleep 30 && kong migrations bootstrap"
    networks:
      - kong-net

  #Konga dashboard
  konga-dashboard:
    image: pantsel/konga
    depends_on:
      - kong
      - konga-mongodb
    restart: unless-stopped
    deploy:
      mode: global
    environment:
      - NODE_ENV=production
      - TOKEN_SECRET=${KONG_TOKEN_SECRET}
      - DB_ADAPTER=mongo
      - DB_HOST=konga-mongodb
      - DB_PORT=27017
      - DB_USER=kong
      # - DB_PASSWORD=kong
      # - DB_DATABASE=kong
    ports:
      - 1337:1337
    networks:
      - kong-net

  konga-mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - kong-net

  #Monitoring
  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    command: -logtostderr -docker_only
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - influx
    deploy:
      mode: global

  zabbix:
    image: zabbix/zabbix-agent
    hostname: '{{.Node.ID}}'
    restart: unless-stopped
    deploy:
      mode: global
    privileged: true
    environment:
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
      - ZBX_METADATAITEM=${ZBX_METADATA}
      - ZBX_HOSTNAME=${ZBX_HOSTNAME}

networks:
  kong-net:

volumes:
  postgres_data:
  mongo_data:
